version: '2.0.0'
services:
  nestjs:
    environment:
      - PORT=${PORT}
      - SOCKETIO_PORT=${SOCKETIO_PORT}
      - WEBSOCKET_PORT=${WEBSOCKET_PORT}
      - DB_DIALECT=${DB_DIALECT}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - JWT_SECRET=${JWT_SECRET}
      - WHATSAPP_API_CONNECT_URL=${WHATSAPP_API_CONNECT_URL}
      - WHATSAPP_API_SEND_MESSAGE_URL=${WHATSAPP_API_SEND_MESSAGE_URL}
    image: api-iot:2.0
    build:
      context: .
      dockerfile: Dockerfile
      target: build
      args:
        PORT: ${PORT}
        SOCKETIO_PORT: ${SOCKETIO_PORT}
        WEBSOCKET_PORT: ${WEBSOCKET_PORT}
    ports: 
      - ${PORT}:${PORT}
      - ${SOCKETIO_PORT}:${SOCKETIO_PORT}
      - ${WEBSOCKET_PORT}:${WEBSOCKET_PORT}
    volumes:
      - /server/node_modules
    restart: always