version: "3.8"

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime   
    image: api-iot:2.0
    container_name: nestjs-api
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
      - "${SOCKETIO_PORT}:${SOCKETIO_PORT}"
      - "${WEBSOCKET_PORT}:${WEBSOCKET_PORT}" 
