version: '1.0.0'
services:
  nestjs:
    environment:
      - PORT=
      - DB_DIALECT=
      - DB_HOST=
      - DB_PORT=
      - DB_USER=
      - DB_PASS=
      - DB_NAME=
      - JWT_SECRET=
    image: api-automation:1.0
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    ports: 
      - 3004:3004