services:
  db:
    image: mysql:8.1
    container_name: mysql-db
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: automation
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:
    driver: local
